export const PANEL_CSS = `
:host{all:initial!important;position:fixed!important;top:20px!important;right:20px!important;z-index:2147483647!important;color-scheme:light!important;font:14px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif!important;color:#202a36!important;}
*{box-sizing:border-box} [hidden]{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;border:0}
.panel{width:360px;max-height:calc(100vh - 40px);display:flex;flex-direction:column;background:#fff;border:1px solid #c7d3df;border-radius:14px;box-shadow:0 12px 42px #12263a35;overflow:hidden}
header{display:flex;align-items:center;gap:6px;padding:12px 14px;border-bottom:1px solid #e3e9ef;background:#f6f9fc}h2{font-size:16px;margin:0;flex:1}h3{font-size:14px;margin:12px 0 6px}
.content{padding:14px;overflow:auto;overscroll-behavior:contain}button,input,select,textarea{font:inherit;color:inherit}button{border:1px solid #bccbd9;background:#fff;border-radius:7px;padding:6px 10px;cursor:pointer}button:hover{background:#edf3fa}button:disabled{opacity:.5;cursor:default}button.primary{background:#245bd1;border-color:#245bd1;color:white}button.danger{color:#b32828}input:not([type=checkbox]),select,textarea{width:100%;padding:8px;border:1px solid #aabccc;border-radius:7px;background:white}textarea{min-height:90px;resize:vertical}input[type=checkbox]{vertical-align:middle}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid #4483ed;outline-offset:2px}
label{display:block;margin:10px 0 5px}.row{display:flex;gap:8px;align-items:center;margin:8px 0;flex-wrap:wrap}.row input{flex:1;min-width:0}p{margin:8px 0}.muted{color:#52677d;font-size:12px}.notice{padding:10px;border-radius:8px;background:#f0f5ff}.warning{background:#fff6e4;color:#725015}.status{font-size:13px;min-height:22px;margin:10px 0}.results{list-style:none;padding:0;margin:8px 0}.result{margin:8px 0;border-left:3px solid #d3a523;background:#fffcf1;border-radius:5px;padding:8px}.result.uncertain{border-left-style:dashed;background:#f3f5f9;border-color:#8998ae}.result button{text-align:left;width:100%;background:transparent;border:0;padding:0}.result button[aria-current=true]{outline:2px solid #d38a24}.quote{white-space:pre-wrap;overflow-wrap:anywhere;display:block;margin-top:4px}.result-meta{display:flex;align-items:baseline;justify-content:space-between;gap:6px;flex-wrap:wrap}.probability{font-size:12px;font-variant-numeric:tabular-nums;white-space:nowrap;color:#36547d;background:#e6edf7;border-radius:4px;padding:1px 5px}.heading{font-weight:600;font-size:12px}.full{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}summary{cursor:pointer;padding:6px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.5 ui-monospace,monospace;background:#f4f6f8;padding:8px;max-height:220px;overflow:auto}a{color:#245bd1}footer{padding:10px 14px;border-top:1px solid #e3e9ef}.collapsed .content,.collapsed footer{display:none}.collapsed{width:240px}
@media(max-width:600px){:host{top:auto!important;bottom:10px!important;right:10px!important;left:10px!important}.panel{width:100%;max-height:60vh}.collapsed{width:100%}}
`;
